### ISSUE TITLE
Сбивается раскраска, перестаёт красить типы правильно

### ISSUE THREAD

**Issue by Oleg-N-Cher** [UA3MQJ/SublimeText3Oberon#1]
![image](https://user-images.githubusercontent.com/1090608/68454000-efd19700-01ff-11ea-9092-a260531db023.png)

Здесь какие соображения будут:

a) в первой процедуре не подсвечивается модификатор IN, хотя в тексте процедуры после BEGIN он бы подсветился (я проверил);

b) во второй процедуре не подсветился уже модификатор VAR (он примерно в той же роли), а также сбилась подсветка типов - BYTE уже не подсвечивается, хотя ниже по тексту он уже подсвечивается;

c) SIZE это встроенная в язык функция. По идее, тоже должна как-то отличаться (тем же цветом, что и остальные ключевые слова типа WHILE).

[Файл Files.Mod текстом, для тестирования подсветки](https://github.com/Oleg-N-Cher/OfrontPlus/blob/master/Lib/Mod/Files.Mod)

Также прошу подсветку символа @ при указании параметров-переменных процедуры. Пример кода:

`Strings.StrToInt(data, @result);`

Такой синтаксис указания ссылочного параметра применяется в нашем диалекте Оберон-3.

**Comment by UA3MQJ** [comment]
Вроде бы исправил. Еще подкорректировал некоторые вещи с array of и pointer и record
